import type { FollowUpTask, Lead, LeadNote, Profile } from "@/lib/types";

const now = new Date();
const dateFromNow = (days: number, hour = 10) => {
  const date = new Date(now);
  date.setDate(date.getDate() + days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
};

export const demoLeads: Lead[] = [
  {
    id: "lead-ana",
    assigned_user_id: "demo-user",
    status_id: "status-contato-feito",
    source_id: "source-landing-page",
    name: "Ana Carolina",
    email: "ana@lumina.com.br",
    phone: "+55 11 98765-1240",
    city: "São Paulo",
    company: "Lumina Arquitetura",
    interest: "Consultoria estratégica",
    budget: 18000,
    preferred_contact_time: null,
    notes: "Busca organizar o processo comercial antes de expandir a equipe.",
    source: "Landing page",
    status: "contato-feito",
    created_at: dateFromNow(-2),
    updated_at: dateFromNow(0),
  },
  {
    id: "lead-carlos",
    assigned_user_id: "demo-user",
    status_id: "status-proposta",
    source_id: "source-indicacao",
    name: "Carlos Mendes",
    email: "carlos@prismaeng.com",
    phone: "+55 21 99127-8412",
    city: "Rio de Janeiro",
    company: "Prisma Engenharia",
    interest: "Desenvolvimento web",
    budget: 12500,
    preferred_contact_time: null,
    notes: null,
    source: "Indicação",
    status: "proposta",
    created_at: dateFromNow(-4),
    updated_at: dateFromNow(-1),
  },
  {
    id: "lead-juliana",
    assigned_user_id: "demo-user",
    status_id: "status-qualificado",
    source_id: "source-instagram",
    name: "Juliana Alves",
    email: "juliana@serenite.com",
    phone: "+55 31 99812-1104",
    city: "Belo Horizonte",
    company: "Serenité Clínica",
    interest: "Gestão de tráfego",
    budget: 7200,
    preferred_contact_time: null,
    notes: null,
    source: "Instagram",
    status: "qualificado",
    created_at: dateFromNow(-1),
    updated_at: dateFromNow(-1),
  },
  {
    id: "lead-rodrigo",
    assigned_user_id: "demo-user",
    status_id: "status-novo",
    source_id: "source-google-ads",
    name: "Rodrigo Freitas",
    email: "rodrigo@axiscont.com",
    phone: "+55 41 98803-9231",
    city: "Curitiba",
    company: "Axis Contabilidade",
    interest: "Consultoria estratégica",
    budget: 9800,
    preferred_contact_time: null,
    notes: null,
    source: "Google Ads",
    status: "novo",
    created_at: dateFromNow(0),
    updated_at: dateFromNow(0),
  },
  {
    id: "lead-mariana",
    assigned_user_id: "demo-user",
    status_id: "status-fechado",
    source_id: "source-formulario-do-site",
    name: "Mariana Costa",
    email: "mariana@novafisio.com",
    phone: "+55 51 99242-6720",
    city: "Porto Alegre",
    company: "Nova Fisio",
    interest: "Desenvolvimento web",
    budget: 15500,
    preferred_contact_time: null,
    notes: null,
    source: "Formulário do site",
    status: "fechado",
    created_at: dateFromNow(-12),
    updated_at: dateFromNow(-3),
  },
  {
    id: "lead-felipe",
    assigned_user_id: "demo-user",
    status_id: "status-novo",
    source_id: "source-landing-page",
    name: "Felipe Rocha",
    email: "felipe@atelieuno.com",
    phone: "+55 85 99912-3401",
    city: "Fortaleza",
    company: "Ateliê Uno",
    interest: "Gestão de tráfego",
    budget: 5400,
    preferred_contact_time: null,
    notes: null,
    source: "Landing page",
    status: "novo",
    created_at: dateFromNow(0),
    updated_at: dateFromNow(0),
  },
  {
    id: "lead-bianca",
    assigned_user_id: "demo-user",
    status_id: "status-qualificado",
    source_id: "source-linkedin",
    name: "Bianca Martins",
    email: "bianca@verdea.com",
    phone: "+55 19 98432-4421",
    city: "Campinas",
    company: "Verdea Paisagismo",
    interest: "Consultoria estratégica",
    budget: 11000,
    preferred_contact_time: null,
    notes: null,
    source: "LinkedIn",
    status: "qualificado",
    created_at: dateFromNow(-3),
    updated_at: dateFromNow(-1),
  },
];

export const demoTasks: FollowUpTask[] = [
  {
    id: "task-1",
    lead_id: "lead-ana",
    title: "Revisar escopo e enviar condição final",
    due_at: dateFromNow(0, 14),
    completed: false,
    priority: "alta",
    lead: { id: "lead-ana", name: "Ana Carolina" },
  },
  {
    id: "task-2",
    lead_id: "lead-carlos",
    title: "Follow-up da proposta comercial",
    due_at: dateFromNow(1, 9),
    completed: false,
    priority: "media",
    lead: { id: "lead-carlos", name: "Carlos Mendes" },
  },
  {
    id: "task-3",
    lead_id: "lead-juliana",
    title: "Agendar reunião de diagnóstico",
    due_at: dateFromNow(1, 15),
    completed: false,
    priority: "media",
    lead: { id: "lead-juliana", name: "Juliana Alves" },
  },
  {
    id: "task-4",
    lead_id: "lead-mariana",
    title: "Enviar materiais de onboarding",
    due_at: dateFromNow(2, 11),
    completed: false,
    priority: "baixa",
    lead: { id: "lead-mariana", name: "Mariana Costa" },
  },
  {
    id: "task-5",
    lead_id: "lead-bianca",
    title: "Confirmar decisores do projeto",
    due_at: dateFromNow(-1, 16),
    completed: true,
    priority: "media",
    lead: { id: "lead-bianca", name: "Bianca Martins" },
  },
];

export const demoNotes: LeadNote[] = [
  {
    id: "note-1",
    lead_id: "lead-ana",
    content:
      "A cliente gostou da proposta e pediu uma opção com acompanhamento mensal. Decisão prevista para esta semana.",
    created_at: dateFromNow(-1, 16),
  },
  {
    id: "note-2",
    lead_id: "lead-ana",
    content:
      "Reunião de diagnóstico concluída. Prioridade: organizar o processo comercial antes da expansão da equipe.",
    created_at: dateFromNow(-2, 11),
  },
];

export const demoProfile: Profile = {
  id: "demo-user",
  full_name: "João Ribeiro",
  company_name: "Ribeiro Consultoria",
  phone: "+55 11 99999-0000",
  public_form_slug: "ribeiro-consultoria",
};
